### ISSUE TITLE
Frame for code segments is incompletely rendered

### ISSUE THREAD

**Issue by gabeusse** [fulstech/markin#34]
Dear Marking support,

When I include code segments that exceed the rendered window size, and then scroll past the current window boundary, the border does not get updated, as shown in the figure. Could you please take a look into this? 

![code_section_border_rendering](https://user-images.githubusercontent.com/29866891/29176227-87f11218-7deb-11e7-935a-022f0a2e961e.png)

Thanks and best,

Juan Eusse

**Comment by gabeusse** [comment]
Btw, there is code on the bottom of the capture, but I cannot show it because it is sensitive.

**Comment by gabeusse** [comment]
Dear support,

will it be any action related to this ticket?

Best,

Juan

**Comment by fulstech** [comment]
Juan,

We sincerely apologize for the long delay. We will have a version this week to fix your pending issues.

Thank you and best regards,
Fulstech Support

**Comment by fulstech** [comment]
@gabeusse,

This bug has been fixed in version 9.0.8.

Thank you so much for using our product. If you have any other request, don't hesitate to let us know. Once again we apologize for any trouble this bug has caused.

Fulstech Support

**Comment by gabeusse** [comment]
Dear support, 

I am still observing the problem in version 9.0.8, as shown in the screenshot:

![codesectionborderrendering](https://user-images.githubusercontent.com/29866891/31379680-41e38618-adaf-11e7-835e-f287a692fd81.jpg)

Could you please take a look at this again?

**Comment by fulstech** [comment]
Hi @gabeusse,

We could not reproduce the issue with version 9.0.8 and 10.0.0. Could you please try to reinstall, or upgrade to version 10.0.0 and check if the issue still happens?

Thank you and best regards,
Markin Support

**Comment by gabeusse** [comment]
Dear support,

We upgraded to the latest Marking plugin this week, and the behavior is still appearing. Please see attachment.

Best,
![code_bug_v10](https://user-images.githubusercontent.com/29866891/32368652-c2909dac-c086-11e7-8836-87677ca3dd6b.jpg)

**Comment by fulstech** [comment]
@gabeusse,

Sorry for the issue. Can you give us a sample content, since we could not reproduce the issue anymore?

![screenshot from 2017-10-30 12-07-54](https://user-images.githubusercontent.com/17452401/32731347-24e0df02-c8bc-11e7-85be-a8230888ebc2.png)

![screenshot from 2017-10-30 12-14-56](https://user-images.githubusercontent.com/17452401/32731354-29e64352-c8bc-11e7-8b62-46c538790f09.png)
